[project]
name = "dora-pyaudio"
version = "0.0.0"
authors = [{ name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com" }]
description = "dora-pyaudio"
license = "MIT License"

[tool.poetry]
packages = [{ include = "dora_pyaudio" }]

[tool.poetry.dependencies]
dora-rs = "^0.3.6"
numpy = ">= 1.0.0"
pyarrow = ">= 5.0.0"
python = ">= 3.8"
pyaudio = ">= 0.1.0"

[tool.poetry.dev-dependencies]
pytest = ">= 6.3.4"
ruff = ">= 0.9.1"


[project.scripts]
dora-pyaudio = "dora_pyaudio.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
