[project]
name = "dora-mujoco-husky"
version = "0.0.0"
authors = [{ name = "Shashwat Patil", email = "email@email.com" }]
description = "dora-mujoco-husky"
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "dora-rs >= 0.3.9",
    "mujoco >= 3.1.6",
    "pyarrow >= 14.0.1"
]

[dependency-groups]
dev = ["pytest >=8.1.1", "ruff >=0.9.1"]

[project.scripts]
dora-mujoco-husky = "dora_mujoco_husky.main:main"
