[workspace]
members = [
  "apis/c/node",
  "apis/python/node",
  "apis/rust/*",
  "apis/rust/operator/macros",
  "binaries/*",
  "examples/rust-dataflow/*",
  "examples/c++-dataflow/*-rust-*",
  "libraries/core",
  "libraries/extensions/message",
  "libraries/extensions/telemetry/*",
  "libraries/extensions/telemetry/*",
  "libraries/extensions/zenoh-logger",
]

[package]
name = "dora-examples"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"

[dev-dependencies]
eyre = "0.6.8"
tokio = "1.20.1"
dora-coordinator = { path = "binaries/coordinator" }
dunce = "1.0.2"

[[example]]
name = "c-dataflow"
path = "examples/c-dataflow/run.rs"

[[example]]
name = "rust-dataflow"
path = "examples/rust-dataflow/run.rs"

[[example]]
name = "cxx-dataflow"
path = "examples/c++-dataflow/run.rs"

[[example]]
name = "python-dataflow"
path = "examples/python-dataflow/run.rs"
