[workspace]
members = [
  "apis/rust/node",
  "apis/rust/operator",
  "apis/rust/operator/macros",
  "apis/python/node",
  "binaries/coordinator",
  "binaries/runtime",
  "libraries/extensions/message",
  "libraries/extensions/telemetry/metrics",
  "libraries/extensions/telemetry/tracing",
  "libraries/core",
  "examples/example-operator",
  "libraries/extensions/zenoh-logger",
]
