[workspace]
members = ["msg-gen", "msg-gen-macro", "python", "ros2-client"]

[package]
name = "dora-ros2-bridge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["generate-messages"]
generate-messages = ["dep:dora-ros2-bridge-msg-gen-macro"]

[dependencies]
array-init = "2.1.0"
dora-ros2-bridge-msg-gen-macro = { path = "msg-gen-macro", optional = true }
serde = { version = "1.0.164", features = ["derive"] }
serde-big-array = "0.5.1"
widestring = "1.0.2"
ros2-client = { path = "ros2-client" }
rustdds = { git = "https://github.com/dora-rs/RustDDS.git", branch = "deserialize-seed" }

[dev-dependencies]
rand = "0.8.5"
futures = { version = "0.3.28", default-features = false }
