[workspace]
members = ["msg-gen"]

[package]
name = "dora-ros2-bridge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2.1.0"
dora-ros2-bridge-msg-gen = { path = "msg-gen" }
serde = { version = "1.0.164", features = ["derive"] }
serde-big-array = "0.5.1"
widestring = "1.0.2"
ros2-client = "0.5.2"
rustdds = "0.8.3"

[dev-dependencies]
rand = "0.8.5"
futures = { version = "0.3.28", default-features = false }
