[workspace]
members = [
  "apis/c/node",
  "apis/python/node",
  "apis/rust/*",
  "apis/rust/operator/macros",
  "binaries/*",
  "examples/example-operator",
  "libraries/core",
  "libraries/extensions/message",
  "libraries/extensions/telemetry/*",
  "libraries/extensions/telemetry/*",
  "libraries/extensions/zenoh-logger",
]
