[workspace]
members = [
  "api/rust/node",
  "api/rust/operator",
  "api/rust/operator/macros",
  "coordinator",
  "message",
  "metrics",
  "tracing",
  "api/python/binding",
  "common",
  "runtime",
  "runtime/examples/example-operator",
  "zenoh-logger",
]
