[package]
name = "dora-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "api",
    "coordinator",
    "common",
    "runtime",
    "coordinator/examples/example-operator",
]

[dependencies]
eyre = "0.6.7"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.23"
structopt = "0.3.26"
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh.git" }
env_logger = "0.9.0"
tokio = { version = "1.17.0", features = ["full"] }
pyo3 = "0.16.1"
futures = "0.3.21"
envy = "0.4.2"
log = "0.4.16"
tokio-stream = { version = "0.1.8", features = ["net"] }
futures-concurrency = "2.0.3"
tokio-util = { version = "0.7.0", features = ["codec"] }
bincode = "1.3.3"
