[workspace]
members = ["cargo:binaries/cli"]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# Don't use --workspace when building
precise-builds = true
# Disable all packages by default
dist = false
