[package]
name = "communication-layer-request-reply"
version.workspace = true
edition = "2021"

[features]

[dependencies]
eyre = "0.6.8"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
