[project]
name = "dora-outtetts"
version = "0.0.0"
authors = []
license = "MIT License"
description = "dora-outtetts"
readme = "README.md"
requires-python = ">=3.10"


[tool.poetry.dependencies]
dora-rs = "^0.3.6"
numpy = "< 2.0.0"
pyarrow = ">= 5.0.0"
python = "^3.10"
outetts = "^0.2.3"
llama-cpp-python = "^0.3.5"

[dependency-groups]
dev = ["pytest >=8.1.1,<9"]

[project.scripts]
dora-outtetts = "dora_outtetts.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
