[project]
name = "dora-outtetts"
version = "0.0.0"
authors = []
description = "dora-outtetts"
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "dora-rs >= 0.3.6",
    "numpy < 2.0.0",
    "pyarrow >= 5.0.0",
    "outetts >= 0.2.3",
    "llama-cpp-python >= 0.3.5",
]

[dependency-groups]
dev = ["pytest >=8.1.1", "ruff >=0.9.1"]

[project.scripts]
dora-outtetts = "dora_outtetts.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
