[package]
name = "dora-operator-api-cxx"
version.workspace = true
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0.73"
dora-operator-api = { workspace = true }
eyre = "0.6.8"
futures = "0.3.21"
rand = "0.8.5"
tokio = { version = "1.20.1", features = ["rt", "macros"] }

[build-dependencies]
cxx-build = "1.0.73"
