[project]
name = "dora-internvl"
version = "0.3.8"
authors = [
    { name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com" },
    { name = "Enzo Le Van", email = "dev@enzo-le-van.fr" },
]
description = "Dora Node for VLM"
readme = "README.md"

[tool.poetry]
packages = [{ include = "dora_internvl" }]

[tool.poetry.dependencies]
python = "^3.7"
dora-rs = "^0.3.6"
numpy = "< 2.0.0"
torch = "^2.2.0"
torchvision = "^0.17"
transformers = "^4.11.3"
pillow = "^10.0.0"
bitsandbytes = "^0.41.0"
einops = "^0.6.1"
einops-exts = "^0.0.4"
timm = "^0.9.12"
sentencepiece = "^0.1.99"

[tool.poetry.scripts]
dora-internvl = "dora_internvl.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
