[package]
name = "rust-dataflow-example-status-node"
version.workspace = true
edition = "2021"
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
dora-node-api = { workspace = true, features = ["tracing"] }
eyre = "0.6.8"
