[package]
name = "rclrust"
version = "0.0.0"
edition = "2018"
authors = ["Yuma Hiramatsu <yuma.hiramatsu@gmail.com>"]

description = "TODO"
repository = "https://github.com/ros2rust/rclrust"
license = "Apache-2.0"
readme = "../README.md"

keywords = ["ROS2"]
categories = ["science::robotics"]

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
rcl-sys = { path = "../rcl-sys", version = "0.0.1" }
rclrust-msg = "0.0.1"
