[project]
name = "dora-piper"
version = "0.3.8"
authors = [{ name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com" }]
description = "Dora Node for using Agilex piper"
readme = "README.md"


[tool.poetry.dependencies]
dora-rs = "^0.3.6"
python = "^3.7"
piper_sdk = "^0.0.8"
numpy = "< 2.0.0"

[dependency-groups]
dev = ["pytest >=8.1.1", "ruff >=0.9.1"]

[project.scripts]
dora-piper = "dora_piper.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
