[project]
name = "dora-distil-whisper"
version = "0.3.8"
authors = [
    { name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com" },
    { name = "Enzo Le Van", email = "dev@enzo-le-van.fr" },
]
description = "Dora dora-distil-whisper"
license = "MIT License"
readme = "README.md"

[tool.poetry]
packages = [{ include = "dora_distil_whisper" }]

[tool.poetry.dependencies]
dora-rs = "^0.3.6"
numpy = "< 2.0.0"
pyarrow = ">= 5.0.0"
transformers = "^4.0.0"
accelerate = "^0.29.2"
torch = "^2.2.0"
python = "^3.7"
modelscope = "^1.18.1"
lightning-whisper-mlx = { version = "^0.0.10", platform = "darwin" }

[tool.poetry.scripts]
dora-distil-whisper = "dora_distil_whisper.main:main"

[tool.poetry.dev-dependencies]
pytest = ">= 6.3.4"
ruff = ">= 0.9.1"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
