[project]
name = "dora-pyorbbecksdk"
version = "0.3.8"
authors = [
    { name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com" },
    { name = "Xiang Yang", email = "Ryu-Yang@qq.com" },
]
description = "Dora Node for capturing video with PyOrbbeck SDK"
readme = "README.md"

[tool.poetry]
packages = [{ include = "dora_pyorbbecksdk" }]

[tool.poetry.dependencies]
dora-rs = "^0.3.6"
python = "^3.7"
numpy = "< 2.0.0"
opencv-python = ">= 4.1.1"


[project.scripts]
dora-pyorbbecksdk = "dora_pyorbbecksdk.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
