[package]
name = "dora-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = { version = "0.1.11", features = ["net"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
futures-concurrency = "7.0.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.86"
shared_memory = "0.12.0"
dora-core = { path = "../../libraries/core" }
