[build-system]
requires = ["maturin>=0.13.2"]
build-backend = "maturin"

[project]
name = "dora-rs-cli"

scripts = { "dora" = "dora_cli:py_main" }


[tool.maturin]
features = ["pyo3/extension-module"]
