[build-system]
requires = ["maturin>=0.13.2"]
build-backend = "maturin"

[project]
name = "dora-rs-cli"
dynamic = ["version"]
scripts = { "dora" = "dora_cli:py_main" }
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.7"
dependencies = ['dora-rs']

[tool.maturin]
features = ["python", "pyo3/extension-module"]
