[package]
name = "dora-node-api-python"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-node-api = { path = "../../rust/node" }
pyo3 = "0.16"
