[package]
name = "dora-node-api-python"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-node-api = { path = "../../rust/node" }
pyo3 = "0.16"
eyre = "0.6"
futures = "0.3.21"
tokio = { version = "1.17.0", features = ["rt", "sync", "macros"] }
serde_yaml = "0.8.23"


[lib]
name = "dora"
crate-type = ["cdylib"]
