[package]
name = "dora-node-api-c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[dependencies]
dora-node-api = { path = "../../rust/node" }
eyre = "0.6.8"
futures = "0.3.21"
