[project]
name = "dora-ugv"
version = "0.3.6"
authors = [{ name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com" }]
description = "Dora Node for using Agilex UGV"
readme = "README.md"


[tool.poetry.dependencies]
dora-rs = "^0.3.6"
python = "^3.7"


[project.scripts]
dora-ugv = "dora_ugv.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
