[project]
name = "dora-vad"
version = "0.3.8"
description = "Dora Node for Text translating using Argostranslate"
readme = "README.md"
authors = [{ name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com" }]

[tool.poetry]
packages = [{ include = "dora_vad" }]

[tool.poetry.dependencies]
dora-rs = "^0.3.6"
numpy = "< 2.0.0"
python = "^3.7"
silero-vad = "^5.1"


[project.scripts]
dora-vad = "dora_vad.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
