[package]
name = "dora-node-api"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = ["zenoh", "iceoryx"]
zenoh = ["communication-layer-pub-sub/zenoh"]
iceoryx = ["communication-layer-pub-sub/iceoryx"]

[dependencies]
eyre = "0.6.7"
once_cell = "1.13.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
thiserror = "1.0.30"
tracing = "0.1.33"
flume = "0.10.14"
communication-layer-pub-sub = { path = "../../../libraries/communication-layer", default-features = false }
uuid = { version = "1.1.2", features = ["v4"] }
capnp = "0.14.9"
dora-message = { path = "../../../libraries/extensions/message" }

[dev-dependencies]
tokio = { version = "1.17.0", features = ["rt"] }
