[package]
name = "dora-node-api"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = ["zenoh", "iceoryx"]
zenoh = ["dep:zenoh", "dep:zenoh-config"]
iceoryx = ["dep:iceoryx-rs"]

[dependencies]
eyre = "0.6.7"
once_cell = "1.13.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
thiserror = "1.0.30"
tracing = "0.1.33"
uuid = "0.8.2"
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh.git", optional = true }
zenoh-config = { git = "https://github.com/eclipse-zenoh/zenoh.git", optional = true }
flume = "0.10.14"

[target.'cfg(unix)'.dependencies]
iceoryx-rs = { git = "https://github.com/eclipse-iceoryx/iceoryx-rs.git", optional = true }

[dev-dependencies]
tokio = { version = "1.17.0", features = ["rt"] }
