[project]
name = "dora-keyboard"
version = "0.3.8"
authors = [
    { name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com" },
    { name = "Enzo Le Van", email = "dev@enzo-le-van.fr" },
]
description = "Dora dora-keyboard"
license = "MIT License"
[tool.poetry]
packages = [{ include = "dora_keyboard" }]

[tool.poetry.dependencies]
dora-rs = "^0.3.6"
numpy = "< 2.0.0"
pyarrow = ">= 5.0.0"
pynput = "^1.6.0"
python = "^3.7"

[project.scripts]
dora-keyboard = "dora_keyboard.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
