[project]
name = "pyarrow-sender"
version = "0.3.8"
authors = [
    { name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com" },
    { name = "Enzo Le Van", email = "dev@enzo-le-van.fr" },
]
description = "Dora pyarrow Sender"
license = "MIT License"

readme = "README.md"

[tool.poetry.dependencies]
dora-rs = "^0.3.6"
numpy = "< 2.0.0"
pyarrow = ">= 5.0.0"
python = "^3.7"

[project.scripts]
pyarrow-sender = "pyarrow_sender.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
