[build-system]
requires = ["maturin>=0.13.2"]
build-backend = "maturin"

[project]
name = "dora-boxes2d-to-pose"
dynamic = ["version"]
license = { text = "MIT" }
requires-python = ">=3.8"

dependencies = ["maturin>=1.8.2"]

scripts = { "dora-boxes2d-to-pose" = "dora_boxes2d_to_pose:py_main" }

[tool.maturin]
features = ["python", "pyo3/extension-module"]
