[package]
name = "dora-message"
version.workspace = true
edition = "2021"
documentation.workspace = true
description.workspace = true
license.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow-schema = { version = "45.0.0", features = ["serde"] }
uhlc = "0.5.1"
serde = { version = "1.0.136", features = ["derive"] }
eyre = "0.6.8"
