[package]
name = "dora-message"
version.workspace = true
edition = "2021"
documentation.workspace = true
description.workspace = true
license.workspace = true

# Building capnp schema script is disabled by default as it requires to install capnp.
# To change the schema install capnp at: https://capnproto.org/install.html
# And comment the following to build the new schema.
build = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow-schema = { version = "45.0.0", features = ["serde"] }
capnp = { version = "0.14.11", features = ["unaligned"] }
uhlc = "0.5.1"
serde = { version = "1.0.136", features = ["derive"] }
eyre = "0.6.8"

[build-dependencies]
capnpc = "0.14"
