[package]
name = "shared-memory-server"
version.workspace = true
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
serde = { version = "1.0.152", features = ["derive"] }
shared_memory = "0.12.0"
raw_sync = "0.1.5"
bincode = "1.3.3"
tracing = "0.1.37"
