[package]
name = "dora-coordinator"
version.workspace = true
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["tracing"]
tracing = ["dep:dora-tracing"]

[dependencies]
bincode = "1.3.3"
dora-node-api = { workspace = true }
eyre = "0.6.7"
futures = "0.3.21"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
tokio = { version = "1.24.2", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["io-util", "net"] }
tokio-util = { version = "0.7.1", features = ["codec"] }
clap = { version = "3.1.8", features = ["derive"] }
uuid = { version = "1.2.1" }
time = "0.3.9"
rand = "0.8.5"
dora-core = { workspace = true }
tracing = "0.1.36"
futures-concurrency = "7.1.0"
zenoh = "0.7.0-rc"
serde_json = "1.0.86"
dora-download = { workspace = true }
dora-tracing = { workspace = true, optional = true }
which = "4.3.0"
communication-layer-request-reply = { workspace = true }
thiserror = "1.0.37"
ctrlc = "3.2.5"
