[package]
name = "dora-node-api-cxx"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[features]
default = ["tracing-subscriber"]
tracing-subscriber = ["dora-node-api/tracing-subscriber"]

[dependencies]
cxx = "1.0.73"
dora-node-api = { workspace = true }
eyre = "0.6.8"

[build-dependencies]
cxx-build = "1.0.73"
