[package]
name = "dora-node-api-cxx"
version.workspace = true
edition = "2021"
documentation.workspace = true
description.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[features]
default = ["tracing"]
tracing = ["dora-node-api/tracing"]
ros2-bridge = []

[dependencies]
cxx = "1.0.73"
dora-node-api = { workspace = true }
eyre = "0.6.8"
dora-ros2-bridge = { workspace = true, features = ["cxx-bridge"] }

[build-dependencies]
cxx-build = "1.0.73"
