[package]
name = "cxx-dataflow-example-node-rust-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.73"
dora-node-api = { version = "0.1.0", path = "../../../apis/rust/node" }
eyre = "0.6.8"
rand = "0.8.5"

[build-dependencies]
cxx-build = "1.0.73"
