[project]
name = "dora-pyrealsense"
version = "0.3.8"
authors = [{ name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com" }]
description = "Dora Node for capturing video with Pyrealsense"
readme = "README.md"

[tool.poetry]
packages = [{ include = "dora_pyrealsense" }]

[tool.poetry.dependencies]
dora-rs = "^0.3.6"
numpy = "< 2.0.0"
opencv-python = ">= 4.1.1"
python = "^3.7"
pyrealsense2 = [
    { version = "2.54.1.5216", platform = "linux" },
    { version = "2.54.1.5216", platform = "windows" },
]
pyrealsense2-macosx = { version = "2.54.2", platform = "darwin" }


[project.scripts]
dora-pyrealsense = "dora_pyrealsense.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
