[project]
name = "dora-microphone"
version = "0.3.8"
authors = [
    { name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com" },
    { name = "Enzo Le Van", email = "dev@enzo-le-van.fr" },
]
description = "Dora dora-microphone"
license = "MIT License"

dependencies = [
    "dora-rs >= 0.3.6",
    "numpy < 2.0.0",
    "pyarrow >= 5.0.0",
    "sounddevice >= 0.4.6",

]

[project.scripts]
dora-microphone = "dora_microphone.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
