[project]
name = "dora-opus"
version = "0.3.8"
description = "Dora Node for Text translating using Opus"
readme = "README.md"
authors = [
    { name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com" },
    { name = "Enzo Le Van", email = "dev@enzo-le-van.fr" },
    { name = "Félix Huang", email = "felix.huang.net@gmail.com" },
]


[tool.poetry.dependencies]
dora-rs = "^0.3.6"
numpy = "< 2.0.0"
python = "^3.7"
transformers = "^4.45"
modelscope = "^1.18.1"
sentencepiece = "^0.1.99"
torch = "^2.2.0"

[project.scripts]
dora-opus = "dora_opus.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
