name: CI-python

# Filter CI as this job will take time.
on:
  push:
    paths:
      - apis/python/**
      - binaries/runtime/**
      - examples/python-dataflow/**
      - examples/python-operator-dataflow/**
  pull_request:
  workflow_dispatch:

env:
  RUST_LOG: trace

jobs:
  examples:
    name: "Python Examples"
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo --version --verbose
      - uses: Swatinem/rust-cache@v2

      - name: "Python Dataflow example"
        run: cargo run --example python-dataflow

      - name: "Python Operator Dataflow example"
        run: cargo run --example python-operator-dataflow

      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: humble
      - run: 'source /opt/ros/humble/setup.bash && echo AMENT_PREFIX_PATH=${AMENT_PREFIX_PATH} >> "$GITHUB_ENV"'
      - name: "python-ros2-dataflow"
        timeout-minutes: 30
        run: |
          source /opt/ros/humble/setup.bash && ros2 run turtlesim turtlesim_node &
          cargo run --example python-ros2-dataflow --features="ros2-examples"
