name: CI-python

# Filter CI as this job will take time.
on:
  push:
    paths:
      - apis/python/**
      - binaries/runtime/**
  pull_request:

jobs:
  examples:
    name: "Python Examples"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Cap'n Proto and libacl-dev
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y capnproto libcapnp-dev libacl1-dev
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.10

      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo --version --verbose
      - uses: Swatinem/rust-cache@v2

      - name: "Python Dataflow example"
        run: cargo run --example python-dataflow
