
name: CI-python

on:
  push:
    branches:
    - main
    paths:
    - apis/python
    - binaries/runtime
    
jobs:

  examples:
    name: "Python Examples"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Cap'n Proto
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y capnproto libcapnp-dev
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
      - name: "Install python dependencies"
        run: examples/python-dataflow/install.sh