name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: humble
    - run: 'source /opt/ros/humble/setup.bash && echo AMENT_PREFIX_PATH=${AMENT_PREFIX_PATH} >> "$GITHUB_ENV"'
    - name: "Build examples"
      timeout-minutes: 30
      run: cargo build --examples
    - name: "Rust standalone"
      timeout-minutes: 30
      run: cargo run --example random_turtle --features="ros2-examples"
    - name: "Rust Dataflow example"
      timeout-minutes: 30
      run: cargo run --example rust-ros2-dataflow --features="ros2-examples"
    - name: "Python Dataflow example"
      timeout-minutes: 30
      run: cargo run --example python-ros2-dataflow --features="ros2-examples"
    - name: "Python Standalone"
      timeout-minutes: 30
      run: python3 examples/python-standalone-bridge/random_turtle.py

