name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Check"
        run: cargo check
      - name: "Build"
        run: cargo build
      - name: "Test"
        run: cargo test

  clippy:
    name: "Clippy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Clippy"
        run: cargo clippy

  rustfmt:
    name: "Formatting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "rustfmt"
        run: cargo fmt -- --check
