name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  RUST_LOG: trace

jobs:
  test:
    name: "Test"
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 60
    steps:
      - name: Print available space (Windows only)
        run: Get-PSDrive
        if: runner.os == 'Windows'
      - name: Override cargo target dir (Windows only)
        run: echo "CARGO_TARGET_DIR=C:\cargo-target" >> "$GITHUB_ENV"
        shell: bash
        if: runner.os == 'Windows'

      - uses: actions/checkout@v3
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo --version --verbose
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        if: runner.os == 'Linux'
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: false
      - name: Free disk Space (Windows)
        if: runner.os == 'Windows'
        run: |
          docker system prune --all -f
          Remove-Item "C:\Android" -Force -Recurse
      - uses: Swatinem/rust-cache@v2
        with:
          cache-provider: buildjet
          cache-on-failure: true
          # only save caches for `main` branch
          save-if: ${{ github.ref == 'refs/heads/main' }}
          cache-directories: ${{ env.CARGO_TARGET_DIR }}

      - name: "Check"
        run: cargo check --all
      - name: "Build (UNIX)"
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: cargo build --all
      - name: "Build (Windows). Remove node python api as it create name collision."
        if: runner.os == 'Windows'
        run: |

          # build libraries crates
          cargo build -p dora-message
          cargo build -p dora-tracing
          cargo build -p dora-metrics
          cargo build -p dora-download
          cargo build -p dora-core
          cargo build -p communication-layer-pub-sub
          cargo build -p communication-layer-request-reply
          cargo build -p shared-memory-server
          cargo build -p dora-arrow-convert

          # build rust API
          cargo build -p dora-operator-api-macros
          cargo build -p dora-operator-api-types
          cargo build -p dora-operator-api
          cargo build -p dora-node-api
          # cargo build -p dora-operator-api-python
          cargo build -p dora-operator-api-c
          cargo build -p dora-node-api-c

          # build binaries crates
          cargo build -p dora-cli
          cargo build -p dora-coordinator
          cargo build -p dora-runtime
          cargo build -p dora-daemon

          # build extension crates
          cargo build -p dora-record
      - name: "Test"
        # Remove Windows as there is `pdb` linker issue.
        # See: https://github.com/dora-rs/dora/pull/359#discussion_r1360268497
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: cargo test --all
      - name: "Test"
        if: runner.os == 'Windows'
        run: cargo test --all --lib

  # Run examples as separate job because otherwise we will exhaust the disk
  # space of the GitHub action runners.
  examples:
    name: "Examples"
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo --version --verbose
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        if: runner.os == 'Linux'
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: false
      - name: Free disk Space (Windows)
        if: runner.os == 'Windows'
        run: |
          docker system prune --all -f
          Remove-Item "C:\Android" -Force -Recurse
      - uses: Swatinem/rust-cache@v2
        with:
          cache-provider: buildjet
          cache-on-failure: true
          # only save caches for `main` branch
          save-if: ${{ github.ref == 'refs/heads/main' }}

      # general examples
      - name: "Build examples"
        timeout-minutes: 30
        run: cargo build --examples
      - name: "Rust Dataflow example"
        timeout-minutes: 30
        run: cargo run --example rust-dataflow
      - name: "Multiple Daemons example"
        timeout-minutes: 30
        run: cargo run --example multiple-daemons
      - name: "C Dataflow example"
        timeout-minutes: 15
        run: cargo run --example c-dataflow
      - name: "C++ Dataflow example"
        timeout-minutes: 15
        run: cargo run --example cxx-dataflow
      - name: "Cmake example"
        if: runner.os == 'Linux'
        timeout-minutes: 30
        run: cargo run --example cmake-dataflow

      # python examples
      - uses: actions/setup-python@v2
        if: runner.os == 'Linux' || runner.os == 'macOS'
        with:
          python-version: "3.8"
      - name: "Python Dataflow example"
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: cargo run --example python-dataflow
      - name: "Python Operator Dataflow example"
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: cargo run --example python-operator-dataflow

  # ROS2 bridge examples
  ros2-bridge-examples:
    name: "ROS2 Bridge Examples"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo --version --verbose
      - uses: Swatinem/rust-cache@v2
        with:
          cache-provider: buildjet
          cache-on-failure: true
          # only save caches for `main` branch
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: humble
      - run: 'source /opt/ros/humble/setup.bash && echo AMENT_PREFIX_PATH=${AMENT_PREFIX_PATH} >> "$GITHUB_ENV"'
      - name: "Rust ROS2 Bridge example"
        timeout-minutes: 30
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          source /opt/ros/humble/setup.bash && ros2 run turtlesim turtlesim_node &
          cargo run --example rust-ros2-dataflow --features="ros2-examples"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: "python-ros2-dataflow"
        timeout-minutes: 30
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          # Reset only the turtlesim instance as it is not destroyed at the end of the previous job
          source /opt/ros/humble/setup.bash && ros2 service call /reset std_srvs/srv/Empty &
          cargo run --example python-ros2-dataflow --features="ros2-examples"

  bench:
    name: "Bench"
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo --version --verbose
      - uses: Swatinem/rust-cache@v2
        with:
          cache-provider: buildjet
          cache-on-failure: true
          # only save caches for `main` branch
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: "Benchmark example"
        timeout-minutes: 30
        run: cargo run --example benchmark --release

  CLI:
    name: "CLI Test"
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo --version --verbose
      - uses: Swatinem/rust-cache@v2
        with:
          cache-provider: buildjet
          cache-on-failure: true
          # only save caches for `main` branch
          save-if: ${{ github.ref == 'refs/heads/main' }}

      # CLI tests
      - name: "Build cli and binaries"
        timeout-minutes: 45
        # fail-fast by using bash shell explictly
        shell: bash
        run: |
          cargo install --path binaries/coordinator --locked
          cargo install --path binaries/daemon --locked
          cargo install --path binaries/cli --locked
      - name: "Test CLI"
        timeout-minutes: 30
        # fail-fast by using bash shell explictly
        shell: bash
        run: |
          dora up
          dora list

          # Test Rust template Project
          dora new test_rust_project --internal-create-with-path-dependencies
          cd test_rust_project
          cargo build --all
          dora start dataflow.yml --name ci-rust-test
          sleep 10
          dora stop --name ci-rust-test
          cd ..

          # Test Python template Project
          pip3 install maturin
          maturin build -m apis/python/node/Cargo.toml
          pip3 install target/wheels/*
          dora new test_python_project --lang python --internal-create-with-path-dependencies
          cd test_python_project
          dora start dataflow.yml --name ci-python-test
          sleep 10
          dora stop --name ci-python-test
          cd ..

          dora destroy

  clippy:
    name: "Clippy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo --version --verbose

      - name: "Clippy"
        run: cargo clippy --all
      - name: "Clippy (tracing feature)"
        run: cargo clippy --all --features tracing
        if: false # only the dora-runtime has this feature, but it is currently commented out
      - name: "Clippy (metrics feature)"
        run: cargo clippy --all --features metrics
        if: false # only the dora-runtime has this feature, but it is currently commented out

  rustfmt:
    name: "Formatting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - name: "rustfmt"
        run: cargo fmt --all -- --check

  check-license:
    name: "License Checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo --version --verbose
      - uses: Swatinem/rust-cache@v2
        with:
          cache-provider: buildjet
          cache-on-failure: true
          # only save caches for `main` branch
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - run: cargo install cargo-lichking
      - name: "Check dependency licenses"
        run: cargo lichking check
