name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Check"
        run: cargo check --all
      - name: "Build"
        run: cargo build --all
      - name: "Test"
        run: cargo test --all

  clippy:
    name: "Clippy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Clippy"
        run: cargo clippy --all

  rustfmt:
    name: "Formatting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "rustfmt"
        run: cargo fmt --all -- --check
