name: Coverage

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  coverage:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            ros_distro: foxy

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}

      - name: Run cargo test
        run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.bash
          cargo test -p rclrust-msg -p rclrust-msg-gen --no-fail-fast
          cargo test -p rclrust --no-fail-fast -- --test-threads 1
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests
          RUSTDOCFLAGS: -Cpanic=abort

      - name: Gather coverage data
        id: coverage
        uses: actions-rs/grcov@v0.1

      - name: Upload coverage data
        uses: codecov/codecov-action@v1
        with:
          file: ${{ steps.coverage.outputs.report }}
          fail_ci_if_error: true
