name: Document

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

concurrency: doc

jobs:
  doc:
    strategy:
      matrix:
        ros:
          - { distro: foxy, os: ubuntu-20.04 }
          - { distro: galactic, os: ubuntu-20.04 }
          - { distro: rolling, os: ubuntu-20.04 }

    runs-on: ${{ matrix.ros.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ matrix.ros.distro }}

      - name: Generate
        run: |
          source /opt/ros/${{ matrix.ros.distro }}/setup.bash
          cargo doc --features $ROS_DISTRO --no-deps

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          destination_dir: ${{ matrix.ros.distro }}/main
