name: Release

permissions:
  contents: write

on:
  release:
    types:
      - "published"

jobs:
  release:
    name: "Release"

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: Install libacl-dev (Linux)
        if: runner.os == 'Linux'
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y libacl1-dev
      - name: Install XCode (macOS)
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      
      # Publish Dora Node Python API
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin==0.14
      - name: Publish wheel
        shell: bash
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
        run: |
          cd apis/python/node
          maturin publish \
          --skip-existing \
          -o wheels \
          --no-sdist \
          --username __token__ \
