name: Rolling

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        rust:
          - 1.53.0 # MSRV
          - stable
          - beta
          - nightly

        include:
          - os: ubuntu-20.04
            ros_distro: rolling

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}

      - name: Run cargo check
        run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.bash
          cargo check --features ${{ matrix.ros_distro }}

      - name: Run cargo test
        run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.bash
          cargo test -p rclrust-msg -p rclrust-msg-gen -p rcl-sys
          cargo test -p rclrust --features ${{ matrix.ros_distro }} -- --test-threads 1
        continue-on-error: ${{ matrix.rust == 'nightly' }}
